In [4]:
import numpy as np
import pandas as pd

np.arange(4.0,step=0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5])

In [5]:
import numpy as np
import pandas as pd

pd.Series(np.arange(4.0,step=0.5))

0    0.0
1    0.5
2    1.0
3    1.5
4    2.0
5    2.5
6    3.0
7    3.5
dtype: float64

In [8]:
import numpy as np
import pandas as pd

s1=pd.Series(np.arange(4.0,step=1.0),index=['a','b','c','d'])
s1

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [24]:
display(s1)
s1[0]

a     0.0
b     1.0
c    18.0
d     9.0
dtype: float64

/tmp/ipykernel_9898/1551149800.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s1[0]


0.0

In [25]:
s1['a']

0.0

In [26]:
s1[['a','b','d']]

a    0.0
b    1.0
d    9.0
dtype: float64

In [20]:
s1[-2:]

c    18.0
d     9.0
dtype: float64

In [19]:
s1[-2:]*2

c    36.0
d    18.0
dtype: float64

In [16]:
s1[-2:]*=2

In [18]:
s1

a     0.0
b     1.0
c    18.0
d     9.0
dtype: float64

In [17]:
s1

a     0.0
b     1.0
c    18.0
d     9.0
dtype: float64

In [27]:
np.reshape(np.arange(16),(4,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [30]:
np.arange(16).reshape((4,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [35]:
data=np.arange(16).reshape((4,4))
dataFrame=pd.DataFrame(data,
            index=['台中','高雄','台北','屏東'],
            columns=['one','two','three','four'])
dataFrame

one  two  three  four
台中    0    1      2     3
高雄    4    5      6     7
台北    8    9     10    11
屏東   12   13     14    15

In [37]:
dataFrame['one']

台中     0
高雄     4
台北     8
屏東    12
Name: one, dtype: int64

In [40]:
dataFrame[['one','two']]

one  two
台中    0    1
高雄    4    5
台北    8    9
屏東   12   13

In [41]:
display(dataFrame)
dataFrame.loc['台北']

one  two  three  four
台中    0    1      2     3
高雄    4    5      6     7
台北    8    9     10    11
屏東   12   13     14    15

one       8
two       9
three    10
four     11
Name: 台北, dtype: int64

In [42]:
dataFrame.loc[['台北','台中']]

one  two  three  four
台北    8    9     10    11
台中    0    1      2     3